# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT api.wsgi

beta_settings:
    cloud_sql_instances: simplenight-api-278418:us-east1:simplenight-api-instance

env_variables:
  DJANGO_DATABASE: "appengine"
  DB_NAME: 'simplenight-api-db'
  DB_USERNAME: 'simplenight'
  DB_PASSWORD: 'daux!bauc7nooc7YIP'
  DB_HOST: '/cloudsql/simplenight-api-278418:us-east1:simplenight-api-instance'

runtime_config:
  python_version: 3
# [END runtime]