timeout: 20m

steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Code'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - echo 'Code analysis'
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'UnitTest'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - echo 'Unit test execution'
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'QADeploy'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    if (( $BRANCH_NAME == "develop" && $PROJECT_ID == "simplenight-api" )); then
      app deploy
    else
      echo "not a develop branch so won't do QA deployment."
    fi
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'RegressionTest'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - echo 'Regression test execution'
