#### REGISTERATIONS
POST http://localhost:8000/api/v1/accounts/register
Content-Type: application/json

{
    "username": "username1223",
    "email": "user1243@developer.com",
    "password1": "p@ass1234",
    "password2": "p@ass1234"
}

##### Login
POST http://localhost:8000/api/v1/accounts/login
Content-Type: application/json

{
    "username":"username1223",
    "password":"p@ass1234"
}



### Reset Password
POST http://localhost:8000/api/v1/accounts/password/reset
Content-Type: application/json

{
    "email": "ilyas@zapdas.co"
}


### User Profile
GET http://localhost:8000/api/v1/accounts/user
Content-Type: application/json
Authorization: token f53cfb5f5feadbc274406c52581d979c84eecb6d




#### ADMIN API GET ALL THE USER

#### 
GET http://localhost:8000/api/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d


##### CREATE USER ADMIN API
POST http://localhost:8000/api/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d

{
    "username":"username123123",
    "password":"password123",
    "email": "user123123@u3ser.com",
    "is_staff":"true",
    "is_superuser":"true",
    "is_active":"true"
}




##### UPDATE USER ADMIN API
PUT http://localhost:8000/api/v1/users/20
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d

{
    "username":"username123123",
    "password":"password123",
    "email": "user123123@u3ser.com",
    "is_staff":"true",
    "is_superuser":"true",
    "is_active":"false"
}



##### DELETE USER ADMIN API
DELETE http://localhost:8000/api/v1/users/20
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d



##### VENUE READ
GET http://localhost:8000/api/v1/venues
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d



##### VENUE READ SPECIFIC
GET http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d


##### VENUE CREATE
POST http://localhost:8000/api/v1/venues
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d

{
    "name": "testing your venue",
    "venue_from": "SN",
    "type": "NIGHT_LIFE",
    "language_code": "en",
    "tags": "testing tags",
    "star_rating": 1,
    "status": "true"
}


##### VENUE UPDATE
PUT http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d

{
    "name": "testing my venue",
    "venue_from": "SN",
    "type": "NIGHT_LIFE",
    "language_code": "en",
    "tags": "testing tags",
    "star_rating": 1,
    "status": "true"
}


##### VENUE DELETE
DELETE http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d





##### VENUE DETAILS 
GET http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4/details
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d



##### VENUE READ SPECIFIC
GET http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4/details/2e9c0058-33f1-47fc-83c7-20926f6224e4
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d


##### VENUE CREATE
POST http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4/details
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d

{
    "name": "testing your venue",
    "venue_from": "SN",
    "type": "NIGHT_LIFE",
    "language_code": "en",
    "tags": "testing tags",
    "star_rating": 1,
    "status": "true"
}


##### VENUE UPDATE
PUT http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d

{
    "name": "testing my venue",
    "venue_from": "SN",
    "type": "NIGHT_LIFE",
    "language_code": "en",
    "tags": "testing tags",
    "star_rating": 1,
    "status": "true"
}


##### VENUE DELETE
DELETE http://localhost:8000/api/v1/venues/2e9c0058-33f1-47fc-83c7-20926f6224e4
Content-Type: application/json
Accept: application/json
Authorization: Token f53cfb5f5feadbc274406c52581d979c84eecb6d


