# Generated by Django 3.0.6 on 2020-06-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geoname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(unique=True)),
                ('iso_country_code', models.CharField(max_length=2)),
                ('location_name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('stars', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GeonameAlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_name_id', models.IntegerField()),
                ('iso_language_code', models.CharField(max_length=2)),
                ('name', models.TextField()),
                ('is_colloquial', models.BooleanField()),
                ('geoname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='api.Geoname', to_field='geoname_id')),
            ],
        ),
    ]
