# Generated by Django 3.0.6 on 2020-06-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateField(auto_now=True)),
                ('checkoutdate', models.DateField(auto_now=True)),
                ('currency', models.CharField(choices=[('US Dollars', 'US DOLLARS')], default='US Dollars', max_length=30)),
                ('language', models.CharField(choices=[('English', 'ENGLISH')], default='US Dollars', max_length=10)),
                ('occupancy', models.IntegerField(default=1, verbose_name=1)),
                ('snpropertyid', models.CharField(default='AAA', max_length=10)),
                ('package', models.BooleanField(default=False)),
                ('Standalone', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geoname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(unique=True)),
                ('iso_country_code', models.CharField(max_length=2)),
                ('location_name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='hotelmappingcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(verbose_name=5)),
                ('hotel_codes', models.IntegerField(default=1, verbose_name=1)),
                ('hotel_name', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True)),
                ('chain_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('destination_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sn_hotel_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplenight_id', models.IntegerField(verbose_name=9)),
                ('provider', models.CharField(max_length=50)),
                ('provider_id', models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='GeonameAlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_name_id', models.IntegerField()),
                ('iso_language_code', models.CharField(max_length=2)),
                ('name', models.TextField()),
                ('is_colloquial', models.BooleanField()),
                ('iatacode', models.CharField(max_length=3)),
                ('geoname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='api.Geoname', to_field='geoname_id')),
            ],
        ),
    ]
