# Generated by Django 3.0.6 on 2020-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sn_city_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplenight_city_id', models.IntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('provider_city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sn_hotel_map',
            name='provider_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sn_hotel_map',
            name='simplenight_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier_hotels',
            name='hotel_codes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplier_hotels',
            name='provider_id',
            field=models.IntegerField(),
        ),
    ]
