# Generated by Django 3.0.6 on 2020-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sn_city_maps',
        ),
        migrations.DeleteModel(
            name='sn_hotel_maps',
        ),
        migrations.AddField(
            model_name='supplier_hotels',
            name='provider_name',
            field=models.CharField(default='HotelBeds', max_length=50),
        ),
    ]
