# Generated by Django 3.0.6 on 2020-06-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_geonamealternatename_newtestfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonamealternatename',
            name='newtestfield',
        ),
    ]
