# Generated by Django 3.0.6 on 2020-05-31 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonamealternatename',
            name='geoname_id',
        ),
        migrations.AlterField(
            model_name='geoname',
            name='geoname_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='geonamealternatename',
            name='geoname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='api.Geoname', to_field='geoname_id'),
        ),
    ]
