# Generated by Django 3.0.6 on 2020-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_geonamealternatename_newtestfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateField(auto_now=True)),
                ('checkoutdate', models.DateField(auto_now=True)),
                ('currency', models.CharField(choices=[('US Dollars', 'US DOLLARS')], default='US Dollars', max_length=30)),
                ('language', models.CharField(choices=[('English', 'ENGLISH')], default='US Dollars', max_length=10)),
                ('occupancy', models.IntegerField(default=1, verbose_name=1)),
                ('snpropertyid', models.CharField(default='AAA', max_length=10)),
                ('package', models.BooleanField(default=False)),
                ('Standalone', models.BooleanField(default=True)),
            ],
        ),
    ]
