# Generated by Django 3.0.6 on 2020-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='mappingcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(verbose_name=5)),
                ('hotel_codes', models.IntegerField(default=1, verbose_name=1)),
                ('hotel_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(blank=True, max_length=20)),
                ('chain_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('destination_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='geoname',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
