# Generated by Django 3.0.6 on 2020-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_supplier_hotels_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_hotels',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
