# Generated by Django 3.0.6 on 2020-07-07 19:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200702_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='sn_images_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_thumbnail_image', models.CharField(max_length=100)),
                ('image_url_path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('image_provider_id', models.CharField(max_length=100)),
                ('simplenight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier_hotels')),
            ],
        ),
    ]
