# Generated by Django 3.0.6 on 2020-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sn_images_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='sn_images_map',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
