# Generated by Django 3.0.6 on 2020-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200618_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingcodes',
            name='category_name',
        ),
        migrations.AddField(
            model_name='mappingcodes',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
