# Generated by Django 3.0.6 on 2020-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200713_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sn_images_map',
            name='image_url_path',
            field=models.CharField(max_length=100),
        ),
    ]
