# Generated by Django 3.0.6 on 2020-07-16 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20200713_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='pmt_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_transaction_id', models.IntegerField(null=True)),
                ('stripe_id', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[['refunded', 'refunded'], ['cancelled', 'cancelled'], ['paid', 'paid']], max_length=50)),
                ('transaction_amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_transaction', to='api.pmt_transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
