# Generated by Django 3.1.2 on 2021-01-26 18:06
import json

from api import logger

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User


def set_defaults_values(events, schema_editor):
    logger.info("Import user data start")
    f = open(settings.BASE_DIR + "/api/resources/users/user_data.json")
    data = json.load(f)
    print(data["users"])
    for user in data["users"]:
        try:
            if not User.objects.filter(username=user["username"]).exits():
                user_obj = User(
                    email=user["email"],
                    username=user["username"],
                    is_staff=user["is_staff"],
                    is_superuser=user["is_superuser"],
                    is_active=user["is_active"],
                )
                user_obj.set_password(user["password"])
                user_obj.save()
        except Exception as e:
            logger.error("User already exists {}".format(e))
    logger.info("Import user data End")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_auto_20210126_1806"),
    ]

    operations = [
        migrations.RunPython(set_defaults_values),
    ]
