# Generated by Django 3.1.2 on 2021-02-10 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_producthotels_productshotelroomdetails_productshotelroompricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityReservation",
            fields=[
                (
                    "activity_reservation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("activity_name", models.TextField()),
                ("activity_code", models.TextField()),
                ("activity_date", models.DateField()),
                ("is_whole_day", models.BooleanField()),
                ("activity_time", models.TimeField(null=True)),
                ("thumbnail", models.TextField(null=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("total_taxes", models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ("total_base", models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ("currency", models.CharField(max_length=3)),
            ],
            options={"db_table": "activity_reservations"},
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("booked", "booked"),
                    ("cancelled", "cancelled"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ActivityReservationItem",
            fields=[
                (
                    "activity_reservation_item_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "activity_reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_reservation",
                        to="api.activityreservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activityreservation",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="activity_reservation", to="api.booking"
            ),
        ),
        migrations.AddField(
            model_name="activityreservation",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="provider", to="api.provider"
            ),
        ),
    ]
